version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocyclo
    - misspell

linters-settings:
  gocyclo:
    min-complexity: 15

formatters:
  enable:
    - gofmt
    - goimports
